version: '3.8'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    command: yarn start:dev
    ports:
      - '4000:4000'
    environment:
      NODE_ENV: development
